### ISSUE TITLE
coveralls-maven-plugin fails on Java 9

### ISSUE THREAD

**Issue by brettwooldridge** [trautonen/coveralls-maven-plugin#112]
Build fails with the following error running under Java 9, probably something to do with their new package restrictions:
```
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report
 (default-cli) on project HikariCP: Execution default-cli of goal org.eluder.coveralls:coveralls-maven-
plugin:4.3.0:report failed: A required class was missing while executing 
org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report: javax/xml/bind/DatatypeConverter
```

**Comment by trautonen** [comment]
http://mail.openjdk.java.net/pipermail/jdk9-dev/2016-May/004309.html

Probably need to use some alternative way to create hex output from bytes so it won't break with Java 9. There are many ways to do it: http://stackoverflow.com/questions/9655181/how-to-convert-a-byte-array-to-a-hex-string-in-java

**Comment by sesuncedu** [comment]
Trade you for  a quick 4.3.1?  

Apache Commons Codec has a utility method  [Hex::encodeHexString](https://commons.apache.org/proper/commons-codec/archives/1.10/apidocs/org/apache/commons/codec/binary/Hex.html#encodeHexString(byte[]))
>public static String encodeHexString(byte[] data)
>Converts an array of bytes into a String representing the hexadecimal values of each byte in order. The returned String will be double the length of the passed array, as it takes two characters to represent any given byte.

Also 
[DigestUtils::md5Hex](https://commons.apache.org/proper/commons-codec/archives/1.10/apidocs/org/apache/commons/codec/digest/DigestUtils.html#md5Hex(java.lang.String)) will generate a hex encoded MD5 hash from a String.

**Comment by sesuncedu** [comment]
PR submitted.  I included a transfer of ownership of any intellectual property rights JIK.

**Comment by lucasdavid** [comment]
I'm not sure if it's a bad idea or not, but adding the following dependency to the `coveralls-maven-plugin` solved this issue for me:
```xml
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.2.3</version>
</dependency>

**Comment by sjoerdtalsma** [comment]
>@trautonen, any update on when a fix for this issue makes its way into an official coveralls-maven-plugin release? If you're uncomfortable with the change in #118, perhaps adding/upgrading the above dependency will do?

:+1: This issue is over a year old and still hurting people
(e.g. [umldoclet build 333](https://travis-ci.org/talsma-ict/umldoclet/builds/382302629))

**Comment by vladak** [comment]
Looks like one man show/project does not work well. This has basically blocked transition of our project to JDK 9+. Maybe some of the https://github.com/coveralls folks can adapt this plugin ?

**Comment by Pr0methean** [comment]
This doesn't seem to affect Travis-CI, but is blocking my migration from Travis to Azure Pipelines.
