### ISSUE TITLE
No coverage report files found.

### ISSUE THREAD

**Issue by kacperduras** [trautonen/coveralls-maven-plugin#124]
Hi. 
I added integration with Coveralls via this Maven plugin (all builds execute on Travis CI) on GitHub public repository:
* Maven settings: [here](https://github.com/FunnyGuilds/FunnyGuilds/blob/master/pom.xml)
* Travis CI Job log: [here](https://travis-ci.org/FunnyGuilds/FunnyGuilds/jobs/310211721#L1803)

Any ideas?

**Comment by CCFenner** [comment]
Seems you have no tests to execute: https://travis-ci.org/FunnyGuilds/FunnyGuilds/jobs/310211721#L1810

**Comment by kacperduras** [comment]
@CCFenner thanks for your help, but we have given up using this solution ;)
