### ISSUE TITLE
Support Coveralls Parallel Flag

### ISSUE THREAD

**Issue by shabino** [trautonen/coveralls-maven-plugin#128]
It should be possible to cause `"parallel":true` to be set in the JSON sent to Coveralls.

**Comment by tdonohue** [comment]
FYI to others looking at running parallel builds (in Travis CI or similar) using `coveralls-maven-plugin`.  Unfortunately, this bug causes Coveralls.io to not recognize the build as parallel **even if you follow the [Coveralls Parallel Builds Webhook instructions](https://docs.coveralls.io/parallel-build-webhook)**.

You can see my experience with this issue at https://github.com/lemurheavy/coveralls-public/issues/1487

Until this issue can be resolved (e.g. via the attached PR), parallel builds won't work correctly with the latest release of `coveralls-maven-plugin`.
