### ISSUE TITLE
Failure when using flat package structure (my.package.name instead of my/package/name)

### ISSUE THREAD

**Issue by smola** [trautonen/coveralls-maven-plugin#27]
I used to have the following source directory: `src/main/java/io.mola.galimatias`. This made coveralls unable to find sources:

[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:2.1.0:cobertura (default-cli) on project galimatias: Build error: Could not find source file io/mola/galimatias/Domain.java from any source directory -> [Help 1]

Changing to `src/main/java/io/mola/galimatias` fixed the problem.

Failure:
https://travis-ci.org/smola/galimatias/jobs/16153713

Successful build after changing the directory structure:
https://travis-ci.org/smola/galimatias/jobs/16154263

It seems the former directory structure is increasingly common, but I'm not sure how much "standard" it is...

**Comment by trautonen** [comment]
Closing this issue as won't fix. Flat package naming is not generally a good idea and this issue hasn't been requested after the initial creation.
