### ISSUE TITLE
JaCoCo report not found when not in default location

### ISSUE THREAD

**Issue by mwanji** [trautonen/coveralls-maven-plugin#60]
In my [pom.xml](https://github.com/mwanji/uncommons-dbutils/blob/0cd581cf7d5377ce7c3ac165d370007785912ab3/pom.xml), I set JaCoCo reports to be generated in a custom location:

```xml
<plugin>
  <groupId>org.jacoco</groupId>
  <artifactId>jacoco-maven-plugin</artifactId>
  <version>0.7.2.201409121644</version>
  <configuration>
    <outputDirectory>${project.reporting.outputDirectory}/${project.version}/jacoco</outputDirectory>
  </configuration>
</plugin>
```
I also configured coveralls-maven-plugin to add the report in the same custom location:

```xml
<plugin>
  <groupId>org.eluder.coveralls</groupId>
  <artifactId>coveralls-maven-plugin</artifactId>
  <version>3.0.1</version>
  <configuration>
    <jacocoReports>
      <param>${project.reporting.outputDirectory}/${project.version}/jacoco</param>
    </jacocoReports>
  </configuration>
</plugin>
```
I get the following [error](https://travis-ci.org/mwanji/uncommons-dbutils/builds/45580118#L1249):

    [ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.0.1:report (default-cli) on project uncommons-dbutils: I/O operation failed: No coverage report files found -> [Help 1]

I am working around it by generating the JaCoCo report in the default location, but it would be great if non-default locations worked, too.

**Comment by chrisbennight** [comment]
I'm seeing the same issue; had to move the output directory back to the default location despite setting it in the configuration.

**Comment by chrisbennight** [comment]
@mwanji 

Got mine working, based on the code just looks like we needed to fully reference the jacoco.xml file, not just the base directory

**Comment by trautonen** [comment]
A bit late answer but as @chrisbennight said you need to reference the actual report file, not just directory. This is because some tools actually provide reports that are compatible with for example cobertura format. So you can use tools like scoverage but actually use them as cobertura reports.

I'll improve the documentation for this part. @mwanji could you try adding the full path to the jacoco.xml file and try again.

**Comment by mwanji** [comment]
I made the change and it works. Thanks for the help, @chrisbennight and @trautonen .
