### ISSUE TITLE
Unprocessable Entity (Couldn't find a repository matching this job.

### ISSUE THREAD

**Issue by avurro** [trautonen/coveralls-maven-plugin#69]
Complete error:
Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.

I know that is an issue already addressed but I can not solve it.

i have added this plugins on pom:
```
            <plugin>
			    <groupId>org.eluder.coveralls</groupId>
			    <artifactId>coveralls-maven-plugin</artifactId>
			    <version>3.1.0</version>
			    <configuration>
			        <repoToken>yourcoverallsprojectrepositorytoken</repoToken>
			    </configuration>
			</plugin>
			<plugin>
			    <groupId>org.codehaus.mojo</groupId>
			    <artifactId>cobertura-maven-plugin</artifactId>
			    <version>2.6</version>
			    <configuration>
			        <format>xml</format>
			        <maxmem>256m</maxmem>
			        <!-- aggregated reports for multi-module projects -->
			        <aggregate>true</aggregate>
			    </configuration>
			</plugin>
```

and at the end of travis.yml file:
```
after_success:
  - mvn clean cobertura:cobertura coveralls:report
```
The peculiarity is that the pom.xml and trevis.yml are on two different levels.

log: https://travis-ci.org/jmapper-framework/jmapper-core/jobs/60708608
repo:https://github.com/jmapper-framework/jmapper-core

**Comment by trautonen** [comment]
Oh, I see this one. Should be simple to fix just by removing the placeholder repository token configuration. Remove this from your `pom.xml`, it's there just for example purpose.
```
<configuration>
    <repoToken>yourcoverallsprojectrepositorytoken</repoToken>
</configuration>
```

Travis CI does not need explicit repository token, but now the placeholder token replaces the automatic service resolution and causes the the upload to fail.

**Comment by avurro** [comment]
ok, it works now, thanks
