### ISSUE TITLE
Verify Cobertura 2.7 JDK8 support

### ISSUE THREAD

**Issue by trautonen** [trautonen/coveralls-maven-plugin#70]
Cobertura should properly support Java 8 since version 2.7. This should be verified and described in the readme. Would be helpful to many who are using Java 8 with multi module projects.

**Comment by trautonen** [comment]
Lambda's fail with invalid syntax. There is also issues in github which conclude that it doesn't work properly:
https://github.com/cobertura/cobertura/issues/166
https://github.com/cobertura/cobertura/issues/248

**Comment by krichter722** [comment]
The README should be adjusted to not point to cobertura as the first choice for code coverage [since it still doesn't seem to support Java >8 due to a deficit in a dependency](https://github.com/cobertura/cobertura/issues/176).
