### ISSUE TITLE
Report submission to Coveralls API failed with HTTP status 500: Internal Server Error

### ISSUE THREAD

**Issue by jknack** [trautonen/coveralls-maven-plugin#72]
Hi,

 Got a 500 error in the last two build. It was working perfectly in the past. Build is available at: https://travis-ci.org/jooby-project/jooby

 Appreciate any help.

Thanks

**Comment by jsotuyod** [comment]
+1, though I don't think it's an issue with this plugin. Both versions 2.0.1 and 3.0.1 show the same result, and there were no breaking API changes in coveralls AFAIK

**Comment by psiniemi** [comment]
+1 Started happening to me yesterday

**Comment by davinkevin** [comment]
Same today

**Comment by jknack** [comment]
it was a coveralls problem (https://github.com/lemurheavy/coveralls-public/issues/549)

now seems happy

**Comment by trautonen** [comment]
Ok. Good to know it's working now. I will close this issue now as it seems it was Coveralls issue.
