### ISSUE TITLE
Report submission to Coveralls API failed with HTTP status 500

### ISSUE THREAD

**Issue by neoremind** [trautonen/coveralls-maven-plugin#75]
Hi there,

I was using coveralls-maven-plugin and it has been a great plugin. I try to integrate with travis ci. My project is maven based and while travis builds successfully and then execute "after-success" procedure, I got the following failure, which seems to have some problems when delivering report via converalls API to its platform. I tried a few times but failure still shows, I suppose it was a stable reproduced issue. So could you please help me figure out? My repo addr is https://github.com/neoremind/navi-pbrpc.

Downloaded: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar (5 KB at 16.5 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar (28 KB at 110.7 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar (14 KB at 51.1 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit/3.4.1.201406201815-r/org.eclipse.jgit-3.4.1.201406201815-r.jar (1862 KB at 6893.1 KB/sec)
[INFO] Starting Coveralls job for travis-ci (69604834)
[INFO] Git commit e80f44f in master
[INFO] Writing Coveralls data to /home/travis/build/neoremind/navi-pbrpc/target/coveralls.json...
[INFO] Processing coverage report from /home/travis/build/neoremind/navi-pbrpc/target/site/cobertura/coverage.xml
[INFO] Successfully wrote Coveralls data in 517ms
[INFO] Gathered code coverage metrics for 71 source files with 7052 lines of code:
[INFO] - 1451 relevant lines
[INFO] - 810 covered lines
[INFO] - 641 missed lines
[INFO] Submitting Coveralls data to API
[ERROR] Submission failed in 4459ms while processing data
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:33 min
[INFO] Finished at: 2015-07-05T10:40:57+00:00
[INFO] Final Memory: 36M/465M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.1.0:report (default-cli) on project navi-pbrpc: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 500: Internal Server Error (Build processing error.) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by trautonen** [comment]
This most likely an issue with Coveralls service. If the 500 error persists after a while, I think you should contact them at info@coveralls.io or via twitter https://twitter.com/CoverallsApp. Today is Sunday, so there might not be anyone to fix anything until tomorrow.

**Comment by neoremind** [comment]
Hi trautonen,
Thanks for your quick response, though it is Sunday today. I will wait and trigger the build to run again tomorrow to see if it works or not. 
Best regards,
Xu

**Comment by davinkevin** [comment]
When the coveralls system is down (like now, in read-only), the submission of cause the build to fail... and it's bad because all the test works.

Is it possible to have an option to prevent the build to fail because of an error in the submission ?

**Comment by trautonen** [comment]
@davinkevin yes, I could add such feature. Created new issue #76 for that.
