### ISSUE TITLE
Property to allow Coveralls service fail without build failure

### ISSUE THREAD

**Issue by trautonen** [trautonen/coveralls-maven-plugin#76]
If you run your tests and coverage in same build and the Coveralls service is down or not working properly (HTTP status 5xx) it will result a failed build. For such cases there could be property that allows Coveralls failure without failing the build. That would lead to successful builds but no coverage submitted.

**Comment by davinkevin** [comment]
Hi, 

With the last version of the coveralls maven module and an error 422 from coveralls.io, my build fails.
It seems this issue only track error 5xx and not 4xx.

You can have my build log here : https://travis-ci.org/davinkevin/Podcast-Server with the following build failure error 
```
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.1.0:report (default-cli) on project PodcastServer: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.) -> [Help 1]
```
And the current status of coveralls.io : 
![image](https://cloud.githubusercontent.com/assets/1970922/12806935/d75b1f28-cb0a-11e5-953f-9bdb0a58a895.png)

**Comment by trautonen** [comment]
I think this is arguable. 4xx errors should be client side errors, but actually Coveralls is returning them when their integration with Travis seems to be broken. I could add 422 to the list of server side failures, because that's what they seem to return. Not sure if you could submit now a report with a hard coded token, or is it same 422 with that too.
