### ISSUE TITLE
Request for HTTP proxy support

### ISSUE THREAD

**Issue by bindul** [trautonen/coveralls-maven-plugin#92]
The plug-in, seems to be using HttpClient without any support for HTTP(s) proxy servers. (see [CoverallsClient](https://github.com/trautonen/coveralls-maven-plugin/blob/master/src/main/java/org/eluder/coveralls/maven/plugin/httpclient/CoverallsClient.java)).

While I completely understand most public CI servers do not need this feature, it is valuable when working behind firewalls and debugging configuration / setup.

Support for proxy settings from maven `settings.xml` would be extremely useful; if not, at least support for command line (`http_proxy=...`) or configuration parameters in the plugin (with user overrides) would work.

**Comment by trautonen** [comment]
@bindul can you test with `4.2.0-SNAPSHOT` version from https://oss.sonatype.org/? There is now support for Maven `settings.xml` based proxy.

**Comment by bindul** [comment]
@trautonen Thank you for a quick fix. Verified the fix works; I can upload coverage information from behind a proxy using the `4.2.0-SNAPSHOT` version of the plugin.

**Comment by trautonen** [comment]
Ok, great to hear. I will do one small feature before releasing 4.2.0.
